# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:7.10
#     working_directory: ~/ocelot/client
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run: npm install
#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}
#       - run: npm run test

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/ocelot/client
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/ocelot/client
    steps:
      - checkout
      - run: echo "Testing"
      - run: npm run test
workflows:
  version: 2
    build_and_test:
      jobs:
        - build
        - test
