version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/ocelot/client
    steps:
      - checkout:
          path: ~/ocelot
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo "npm installing"
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/ocelot/client
    steps:
      - checkout:
          path: ~/ocelot
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: echo "Testing"
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
